#ifndef BIN_DEMO_ENUMERABLES_H
#define BIN_DEMO_ENUMERABLES_H

enum messageTypeEnum
{
  REGISTER_CLIENT = 0x04,
  CLIENT_REGISTERED,
  UPDATE_CREDENTIALS,
  ADD_BRICK,
  GAME_FRAME,
  ERROR,
  BRICK_ROW_ASSIGNMENT,
  CONTROLLER_CONTROL_REMOVED,
  GAME_TICK,
  PLAYER_MOVE,
  RESTART_GAME,
  REMOVE_PLAYER_CONTROLLER,
  BACK_TO_LOBBY,
  ART_FRAME
};

enum clientTypeEnum
{
  GAMEBOARD = 0x01,
  BRICK_CONTROLLER,
  PLAYER_CONTROLLER,
  TOUCH_CONTROLLER,
  ADMIN,
  MULTI_BRICK_CONTROLLER
};
#endif