
export enum messageTypeEnum {
  REGISTER_CLIENT = 0x04,
  CLIENT_REGISTERED,
  UPDATE_CREDENTIALS,
  ADD_BRICK,
  GAME_FRAME,
  ERROR,
  BRICK_ROW_ASSIGNMENT,
  CONTROLLER_CONTROL_REMOVED
}

export enum clientTypeEnum {
  GAMEBOARD = 0x01,
  BRICK_CONTROLLER,
  PLAYER_CONTROLLER,
  TOUCH_CONTROLLER
}
