
export enum messageTypeEnum {
  REGISTER_CLIENT = 0x04,
  CLIENT_REGISTERED,
  UPDATE_CREDENTIALS,
  ADD_BRICK,
  GAME_FRAME,
  ERROR,
  BRICK_ROW_ASSIGNMENT,
  CONTROLLER_CONTROL_REMOVED,
  GAME_TICK,
  PLAYER_MOVE
}

export enum clientTypeEnum {
  GAMEBOARD = 0x01,
  BRICK_CONTROLLER,
  PLAYER_CONTROLLER,
  TOUCH_CONTROLLER
}

export enum directionEnum {
  UP = 0x01,
  DOWN,
  LEFT,
  RIGHT
}

export enum errorTypes {
  PLAYER_ID_INCORRECT
}